### ISSUE TITLE
Exports for getting the accounts

### ISSUE THREAD

**Issue by Mirrrrrow** [esx-framework/esx_addonaccount#11]
Hey, I'm a big fan of *not* nesting and generally keeping everything clean with only few indents.
Take this for example:
```
-- 😢😢
TriggerEvent('esx_addonaccount:getSharedAccount', 'society_police', function(account)
    account.addMoney(50)
end)

-- 😁😁😁
local account = exports['esx_addonaccount']:getSharedAccount('society_police')
account.addMoney(50)
```

Would this be an idea to implement, would it be merged if I would make a pr about it?
I know a lot of people prefer using this type of syntax, so I'm asking before doing it.

**Comment by Gellipapa** [comment]
@Mirrrrrow Hi! You can do it but I think where these scripts are used they are used to using events, but if you want you can do it, but keep the old event logic for compatibility.
