### ISSUE TITLE
Society Money goes back to Original

### ISSUE THREAD

**Issue by TrymTube** [esx-framework/esx_addonaccount#6]
So we have bought a Casino Script where you can buy Casino Chips of course and the amount of money gets inserted into the database via database insert from the Casino. the Money changes in the database but it does not when I check my Balance in my Society via Bossmenu ingame. This is because the Casino used a "bypass" by doing the insert itself because neither esx_addonaccount nor esx_society offers a serverside function or event to update, give, remove or check the balance

**Comment by prvtfly** [comment]
Hey TrymTube, you may recommend the authors of the scripts to use `esx_addonaccount:refreshAccounts`.

**Comment by Gellipapa** [comment]
@TrymTube Hi! What do you mean? I don't quite understand. So there is an amount that is entered in the DB but not updated for you? 

If you manually enter the data into the DB then we can't detect that the amount is a changes, use the built in events and everything will work perfectly.

**Comment by Gellipapa** [comment]
Closed because doesn't reply issue author.
