### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Harry755** [esx-framework/esx_addonaccount#7]
[script:esx_addonacco] SCRIPT ERROR: @esx_addonaccount/server/main.lua:18: table index is nil
[script:esx_addonacco] > handler (@esx_addonaccount/server/main.lua:18)
[script:esx_addonacco] > rawQuery (@oxmysql/dist/build.js:25047)
[script:esx_addonacco] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Gellipapa** [comment]
@Harry755 Hi! Very interesting your all scripts not working. You should install your server from scratch in txadmin. Don't use old resources and database.
